server {
  listen 80;
  server_name localhost;

  location /vntrip/ {
    alias /usr/share/nginx/html/vntrip/;
    index index.html;
    try_files $uri $uri/ /vntrip/index.html;

    location ~* \.(ico|png|jpg|jpeg|gif|svg|js|css|json)$ {
            expires 1y;
            add_header Cache-Control "public, no-transform";
            access_log off;
            try_files $uri =404;
    }
  }

  location = /vntrip {
    return 301 /vntrip/;
  }
}
